zylius_user_homepage:
    path:     /user
    defaults: { _controller: ZyliusParduotuveBundle:UserCRUD:read }

zylius_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: ZyliusParduotuveBundle:UserCRUD:update }

zylius_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: ZyliusParduotuveBundle:UserCRUD:delete }

zylius_order_homepage:
    path:     /order
    defaults: { _controller: ZyliusParduotuveBundle:OrderCRUD:read }

zylius_order_edit:
    path:     /order/edit/{id}
    defaults: { _controller: ZyliusParduotuveBundle:OrderCRUD:update }

zylius_order_confirm:
    path:     /order/confirm/{id}
    defaults: { _controller: ZyliusParduotuveBundle:OrderCRUD:confirm }

zylius_order_delete:
    path:     /order/delete/{id}
    defaults: { _controller: ZyliusParduotuveBundle:OrderCRUD:delete }

zylius_order_statistics:
    path:     /order/statistics
    defaults: { _controller: ZyliusParduotuveBundle:OrderCRUD:statistics }

zylius_parduotuve_bucket:
    path:     /bucket
    defaults: { _controller: ZyliusParduotuveBundle:ProductCRUD:readBucket }

zylius_parduotuve_homepage:
    path:     /{page}
    defaults: { _controller: ZyliusParduotuveBundle:ProductCRUD:read, page: 0}

zylius_admin_homepage:
    path:     /admin/logs/{page}
    defaults: { _controller: ZyliusParduotuveBundle:Admin:index, page: 0 }

zylius_admin_add_product:
    path:     /admin/createProduct
    defaults: { _controller: ZyliusParduotuveBundle:ProductCRUD:create }

zylius_admin_delete_product:
    path:     /admin/deleteProduct
    defaults: { _controller: ZyliusParduotuveBundle:ProductCRUD:delete }
    methods:  [POST]
